// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using password_manager_backend.Data;

namespace password_manager_backend.Migrations
{
    [DbContext(typeof(password_manager_backendContext))]
    [Migration("20210813215632_UserInfoModelAddedToSaveAccountInfoModel")]
    partial class UserInfoModelAddedToSaveAccountInfoModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("password_manager_backend.Models.SaveAccountInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserInfoModelId")
                        .HasColumnType("int");

                    b.Property<string>("savedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("savedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("savedUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoModelId");

                    b.ToTable("SaveAccountInfoModel");
                });

            modelBuilder.Entity("password_manager_backend.Models.UserInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("userEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInfoModel");
                });

            modelBuilder.Entity("password_manager_backend.Models.UserLoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserLoginModel");
                });

            modelBuilder.Entity("password_manager_backend.Models.SaveAccountInfoModel", b =>
                {
                    b.HasOne("password_manager_backend.Models.UserInfoModel", "UserInfoModel")
                        .WithMany()
                        .HasForeignKey("UserInfoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfoModel");
                });
#pragma warning restore 612, 618
        }
    }
}
